### ISSUE TITLE
JcApplicationGraphImpl.callers() throws "not found" exception when used on standard library

### ISSUE THREAD

**Issue by volivan239** [UnitTestBot/jacodb#59]
Calling `JcApplicationGraphImpl.callers()` for some standard java methods leads to different `not found` exceptions. For example,

```Kotlin
@Test
fun `analyse something`() = runBlocking {
    val graph = JcApplicationGraphImpl(cp, cp.usagesExt())
    val callers = graph.callers(cp.findClass<java.util.StringTokenizer>().constructors[2])
    println(callers.toList().size)
}
```

throws the following exception:
```
java.lang.IllegalStateException: com.sun.org.apache.xalan.internal.xsltc.compiler.Output#DUP not found
	at org.jacodb.impl.cfg.JcGraphBuilder.visitJcRawFieldRef(JcGraphBuilder.kt:503)
	at org.jacodb.impl.cfg.JcGraphBuilder.visitJcRawFieldRef(JcGraphBuilder.kt:176)
	at org.jacodb.api.cfg.JcRawFieldRef.accept(JcRawInst.kt:832)
	at org.jacodb.impl.cfg.JcGraphBuilder.visitJcRawAssignInst(JcGraphBuilder.kt:237)
```

**Environment**

* SDK: Corretto 11.0.16

**Comment by lehvolk** [comment]
fixed in branch
